# Default values for waorder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullname: waOrder-deployment
labels: waOrder
replicaCount: 3
selectorLabels: waOrder

image:
  repository: ilhamsabir/adsch-be:tagname
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 8081
